/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#ffffff",
        "surface-container": "#f8fafc",
        "surface-container-high": "#eef3f9",
        "surface-container-highest": "#e2eaf4",
        "surface": "#f5f8fc",
        "surface-bright": "#e8f0fb",
        "surface-dim": "#edf2f8",
        "surface-variant": "#dce5ef",
        "surface-tint": "#1d4ed8",
        "background": "#f5f8fc",
        "on-surface": "#17243a",
        "on-surface-variant": "#52627a",
        "on-background": "#17243a",
        "inverse-surface": "#17243a",
        "inverse-on-surface": "#ffffff",
        "primary": "#1d4ed8",
        "primary-container": "#2563eb",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffffff",
        "primary-fixed": "#dbeafe",
        "primary-fixed-dim": "#bfdbfe",
        "on-primary-fixed": "#172554",
        "on-primary-fixed-variant": "#1e40af",
        "inverse-primary": "#0053db",
        "secondary": "#475569",
        "secondary-container": "#e2e8f0",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#334155",
        "secondary-fixed": "#e2e8f0",
        "secondary-fixed-dim": "#cbd5e1",
        "on-secondary-fixed": "#1e293b",
        "on-secondary-fixed-variant": "#475569",
        "tertiary": "#0369a1",
        "tertiary-container": "#dbeafe",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#075985",
        "tertiary-fixed": "#e0f2fe",
        "tertiary-fixed-dim": "#bae6fd",
        "on-tertiary-fixed": "#082f49",
        "on-tertiary-fixed-variant": "#075985",
        "error": "#b42318",
        "warning": "#92400e",
        "error-container": "#fee4e2",
        "on-error": "#ffffff",
        "on-error-container": "#7a271a",
        "outline": "#94a3b8",
        "outline-variant": "#cbd5e1"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4.5rem",
        "container-max": "1280px",
        "gutter-desktop": "1.5rem",
        "gutter-mobile": "1rem"
      },
      fontFamily: {
        "label-badge": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caption": ["Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "code-telemetry": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "display-hero": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "label-badge": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-caption": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "code-telemetry": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display-hero": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-hero-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "800" }]
      }
    },
  },
  plugins: [],
}
