/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0a0e17",
        "surface-container-low": "#181b25",
        "surface-container": "#1c1f29",
        "surface-container-high": "#262a34",
        "surface-container-highest": "#31353f",
        "surface": "#0f131c",
        "surface-bright": "#353943",
        "surface-dim": "#0f131c",
        "surface-variant": "#31353f",
        "surface-tint": "#b4c5ff",
        "background": "#0f131c",
        "on-surface": "#dfe2ef",
        "on-surface-variant": "#c3c6d7",
        "on-background": "#dfe2ef",
        "inverse-surface": "#dfe2ef",
        "inverse-on-surface": "#2c303a",
        "primary": "#b4c5ff",
        "primary-container": "#2563eb",
        "on-primary": "#002a78",
        "on-primary-container": "#eeefff",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        "inverse-primary": "#0053db",
        "secondary": "#bec6e0",
        "secondary-container": "#3f465c",
        "on-secondary": "#283044",
        "on-secondary-container": "#adb4ce",
        "secondary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary": "#7bd0ff",
        "tertiary-container": "#00759f",
        "on-tertiary": "#00354a",
        "on-tertiary-container": "#e1f2ff",
        "tertiary-fixed": "#c4e7ff",
        "tertiary-fixed-dim": "#7bd0ff",
        "on-tertiary-fixed": "#001e2c",
        "on-tertiary-fixed-variant": "#004c69",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "outline": "#8d90a0",
        "outline-variant": "#434655"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4.5rem",
        "container-max": "1280px",
        "gutter-desktop": "1.5rem",
        "gutter-mobile": "1rem"
      },
      fontFamily: {
        "label-badge": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caption": ["Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "code-telemetry": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "display-hero": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "label-badge": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-caption": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "code-telemetry": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display-hero": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-hero-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "800" }]
      }
    },
  },
  plugins: [],
}
